// <auto-generated />
using System;
using MantenimientoFlota.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MantenimientoFlota.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MantenimientoFlotaDbContext))]
    partial class MantenimientoFlotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaActivoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("KilometrajeActual")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorReferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaActivoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Activos", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.CategoriaActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IntervaloMantenimientoKm")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasActivo", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionesGenerales")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Repuestos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Repuestos_StockActual_NoNegativo", "[StockActual] >= 0");

                            t.HasCheckConstraint("CK_Repuestos_StockMinimo_NoNegativo", "[StockMinimo] >= 0");
                        });
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.RepuestoProveedor", b =>
                {
                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioOfrecido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TiempoEntregaDias")
                        .HasColumnType("int");

                    b.HasKey("RepuestoId", "ProveedorId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("RepuestoProveedores", null, t =>
                        {
                            t.HasCheckConstraint("CK_RepuestoProveedores_PrecioOfrecido_NoNegativo", "[PrecioOfrecido] >= 0");

                            t.HasCheckConstraint("CK_RepuestoProveedores_TiempoEntregaDias_NoNegativo", "[TiempoEntregaDias] >= 0");
                        });
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("TarifaPorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.TecnicoEspecialidad", b =>
                {
                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaObtencion")
                        .HasColumnType("date");

                    b.Property<string>("NivelCertificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TecnicoId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("TecnicoEspecialidades", (string)null);
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Activo", b =>
                {
                    b.HasOne("MantenimientoFlota.Domain.Entities.CategoriaActivo", "CategoriaActivo")
                        .WithMany("Activos")
                        .HasForeignKey("CategoriaActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaActivo");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.RepuestoProveedor", b =>
                {
                    b.HasOne("MantenimientoFlota.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("RepuestoProveedores")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MantenimientoFlota.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany("RepuestoProveedores")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.TecnicoEspecialidad", b =>
                {
                    b.HasOne("MantenimientoFlota.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("TecnicoEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MantenimientoFlota.Domain.Entities.Tecnico", "Tecnico")
                        .WithMany("TecnicoEspecialidades")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.CategoriaActivo", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("TecnicoEspecialidades");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("RepuestoProveedores");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Repuesto", b =>
                {
                    b.Navigation("RepuestoProveedores");
                });

            modelBuilder.Entity("MantenimientoFlota.Domain.Entities.Tecnico", b =>
                {
                    b.Navigation("TecnicoEspecialidades");
                });
#pragma warning restore 612, 618
        }
    }
}
